services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:?err}_nginx
    environment:
      - TZ=Europe/Moscow
    volumes:
      - './etc/nginx/templates:/etc/nginx/templates'
      - './etc/nginx/snippets:/etc/nginx/snippets'
      - './etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf'
      - '../var/log/nginx:/var/log/nginx'
      - '../:/var/www/html'
    ports:
      - '${NGINX_PORT}:80'
    links:
      - php
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  php:
    restart: always
    depends_on:
      composer:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: ./php.Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:?err}_php
    environment:
      - TZ=Europe/Moscow
    volumes:
      - '../:/var/www/html'
      - './etc/php/php.ini:/usr/local/etc/php/php.ini'
      - './etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
      - '../var/log/php:/var/log/php'
    expose:
      - 9000
    logging:
      driver: "none"

  composer:
    build:
      context: .
      dockerfile: composer.Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:?err}_composer
    volumes:
      - '../:/var/www/html'
    command: bash -c 'cd /var/www/html && composer update --no-scripts --no-autoloader --ignore-platform-reqs && composer dump-autoload && chown -R www-data:www-data /var/www/html/vendor'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    restart: always
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:?err}_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER?:err}
      POSTGRES_DB: ${POSTGRES_DB?:err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?:err}
    volumes:
      - 'db:/var/lib/postgresql/data'
      - './etc/postgres/initdb.d:/docker-entrypoint-initdb.d/'
    ports:
      - '${POSTGRES_PORT}:5432'

volumes:
  db:
